package com.dani.doctorappointment.core.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
@AllArgsConstructor
public enum GenericEnumException {

    // 4XX
    OPENING_TIME_MALFORMED_ARRANGEMENT_EXCEPTION("001_4XX", "END TIME SHOULD BE GREATER THAN START TIME", HttpStatus.BAD_REQUEST),
    APPOINTMENT_NOT_FOUNT_EXCEPTION("002_4XX", "AN OPENING NOT FOUND EXCEPTION", HttpStatus.NOT_FOUND),
    APPOINTMENT_IS_TAKEN_EXCEPTION("003_4XX", "APPOINTMENT IS TAKEN BY A PATIENT EXCEPTION", HttpStatus.NOT_ACCEPTABLE),
    CAN_NOT_DELETE_CONCURRENT_APPOINTMENT_EXCEPTION("004_4XX", "CAN NOT DELETE A CONCURRENT RESERVING APPOINTMENT", HttpStatus.CONFLICT),
    INVALID_INPUT_EXCEPTION("005_4XX", "NOT A VALID INPUT", HttpStatus.BAD_REQUEST),
    PATIENT_NOT_FOUNT_EXCEPTION("006_4XX", "PATIENT NOT FOUND EXCEPTION", HttpStatus.NOT_FOUND),

    // 5XX,
    SAVE_APPOINTMENT_EXCEPTION("001_5XX", "SAVE ACTUAL OPENING EXCEPTION", HttpStatus.INTERNAL_SERVER_ERROR),
    FIND_ALL_APPOINTMENT_EXCEPTION("002_5XX", "FIND ALL OPENING EXCEPTION", HttpStatus.INTERNAL_SERVER_ERROR),
    DELETE_APPOINTMENT_EXCEPTION("003_5XX", "DELETE OPENING EXCEPTION", HttpStatus.INTERNAL_SERVER_ERROR),
    SAVE_PATIENT_EXCEPTION("004_5XX", "SAVE PATIENT EXCEPTION", HttpStatus.INTERNAL_SERVER_ERROR),

    ;

    private final String errorCode;
    private final String message;
    private final HttpStatus httpStatus;
}
